# Generated by Django 4.0.3 on 2022-05-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0002_profile_email1_profile_name_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
